"""empty message

Revision ID: 835665cd5269
Revises: c2c0450f39d2
Create Date: 2017-11-06 15:25:53.331712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835665cd5269'
down_revision = 'c2c0450f39d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('childservice_action',
    sa.Column('childservice_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['childservice_id'], ['childservice.id'], ),
    sa.PrimaryKeyConstraint('childservice_id', 'action_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('childservice_action')
    op.drop_table('action')
    # ### end Alembic commands ###
